// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicOrganizer.DataAccess;

namespace MusicOrganizer.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("MusicOrganizer.Entities.Song", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Album")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.Property<string>("Art")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bemerkungen")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CD")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Interpret")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.Property<int?>("Jahr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Komponist")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.Property<int?>("LP")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.Property<int?>("single")
                        .HasColumnType("INTEGER");

                    b.HasKey("SongId");

                    b.ToTable("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
